# Site-wide Config

title                : Skye Kychenthal
description          : Skye Kychenthal's professional website including a publications page
locale               : en_US
google_analytics     : UA-200647300-2
keywords:
  - SkyMocha
  - Skye Kychenthal
  - Skye Kychenthal Publications
  - SkyMocha Website
tags:
  - SkyMocha
  - Skye Kychenthal
  - Skye Kychenthal Website
  - SkyMocha Website

encoding             : "utf-8"

exclude              :
  - "/update.py"
  - ".gitignore"
  - ".prettierignore"
  - "/pub_temp.html"
  - "README.md"
  - /old/*

twitter              :
  username           : &twitter 
og_image             : "/assets/imgs/CatEarsThumb.png"
image                : "/assets/imgs/CatEarsThumb.png"

defaults:
  - scope            : 
      path           : "publications.md"
    values           :
      title          : "Skye Kychenthal Publications"
      description    : "Skye Kychenthal Publications including Why The Trans Programmer and Fight Club's Incel To Exploitable Chad Pipeline"
  - scope            : 
      path           : "reading.md"
    values           :
      title          : "Skye Kychenthal Recommended Readings"
      description    : "Skye Kychenthal's Recommended Reading List including Fight Club, Midnf*ck, Disco Elysium, and more!"
      og_description : "Skye Kychenthal's Recommended Reading List including Fight Club, Midnf*ck, Disco Elysium, and more!"
      og_title       : "Skye Kychenthal Recommended Readings"
  - scope            : 
      path           : "Courses/Hum110/Bible_Experiment.md"
    values           :
      title          : "Skye Kychenthal's Bible Experiment"
      description    : "Exploration of Genesis through the lens of Mindf*ck by Christopher Wylie & HumanKind by Rutger Bregman to test hypotheses regarding alt-right radicalization and a theocratic theory of naivete"
      og_description : "Exploration of Genesis through the lens of Mindf*ck by Christopher Wylie & HumanKind by Rutger Bregman to test hypotheses regarding alt-right radicalization and a theocratic theory of naivete"
      og_title       : "Skye Kychenthal's Bible Experiment"
  - scope            : 
      path           : "Courses/Hum110/God_Becomes_The_Police_State.md"
    values           :
      title          : "Skye Kychenthal's Paper: God Becomes The Police State"
      description    : "Exploration of Genesis, specifically the story of Cain and Abel, through the lens of Focault's Discipline & Punish, Rutger Bregman's Humankind, and George Orwell's 1984."
      og_description : "Exploration of Genesis, specifically the story of Cain and Abel, through the lens of Focault's Discipline & Punish, Rutger Bregman's Humankind, and George Orwell's 1984."
      og_title       : "Skye Kychenthal's Paper: God Becomes The Police State"
  - scope            : 
      path           : "Courses"
    values           :
      title          : "Skye Kychenthal Course Notes"
      description    : "Skye Kychenthal's course notes for their Reed College courses"
      og_description : "Skye Kychenthal's course notes for their Reed College courses"
      og_title       : "Skye Kychenthal Course Notes"


author:
  name               : "Skye Kychenthal"
  avatar             : "/assets/imgs/CatEarsThumb.png"
  location           : "NYC & PDX"
  googlescholar      : "https://scholar.google.com/citations?user=GGoRK98AAAAJ"
  email              : "skychenthal@gmail.com"
  github             : "skymocha"
  instagram          : "skymochi64"
  linkedin           : "skymocha"
  orcid              : "https://orcid.org/0000-0001-9770-9224"
  twitter            : "skymochi64"
  youtube            : "SkyMocha"
